# Site
repository: nuritnt/cv
favicon: images/favicon.ico

# Personal info
name: Tuğçe Nur Taş
title: Software Engineer
email: hello@tnt.click
phone: +4179 843 18 28
website: www.tnt.click

# Social links
twitter_username: nuritnt
github_username: nuritnt
linkedin_username: nuritnt
stackoverflow_username: "11361807"

# Additional icon links
additional_links:
  - title: Codepen
    icon: fa-codepen
    url: https://codepen.io/nuritnt

# About Section
about_title: Über mich
about_profile_image: images/profile.jpg
about_content: |
  Selam, ich bin Tuğçe Nur und arbeite als Software Engineer bei der Beratungs- und Entwicklungsagentur Panter AG.
  Im Scrum Team realisiere ich Web-Applikationen, Single-Page-Webanwendungen oder Mobile Apps.
  Durch meine Erfahrungen mit unterschiedlichen Arten von Kunden (Start-Ups, KMU's, Grossfirmen) bin ich sehr anpassungsfähig und arbeite mich gerne und selbstständing in neue Technologien ein.

  **Ich bin "curious by default" und packe gerne Herausforderungen an.**

  Geburtsdatum: 18. November 1991\
  Nationalität: Schweiz & Türkei\
  Sprachen: Deutsch, Englisch, Türkisch, Französisch (Grundlagen)

# Projects Section
projects_title: Technologien

# Experience Section
experience_title: Berufserfahrung

# Education Section
education_title: Ausbildung

# More Section
more_title: Mehr über mich
more_content: |
  **Volunteering**:
  - Coach & Mentor an Events/Workshops für Programmier-Anfänger*innen (CodeExcursion, Rails Girls, Master21)
  - GemüseAckerdemie: Ackern für Bildung und Ernährung. Mit Kindern und Jugendlichen gärtnern und somit die Wertschätzung von Lebensmitteln stärken.

  **Hobbies**:
  - Vogelbeobachtung/Hobby-Ornithologen-Anfängerin
  - Mechanical Keyboards
  - Konzerte

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
